// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb7QD9AnVNc66nFy558eccRHdMnMPnRSA',
    appId: '1:663044881481:web:3a5f7e620378bf2bec9398',
    messagingSenderId: '663044881481',
    projectId: 'store-attendance-a7f2e',
    authDomain: 'store-attendance-a7f2e.firebaseapp.com',
    storageBucket: 'store-attendance-a7f2e.firebasestorage.app',
    measurementId: 'G-L4663MMMX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAojI2JLUKSqGTU41l4Va8tMSZf2Cq-e88',
    appId: '1:663044881481:android:09ccff5438523a5bec9398',
    messagingSenderId: '663044881481',
    projectId: 'store-attendance-a7f2e',
    storageBucket: 'store-attendance-a7f2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsetBFhJ1AiFRD382RmOc59nxY3i0oNag',
    appId: '1:663044881481:ios:db33bc21fb1551fbec9398',
    messagingSenderId: '663044881481',
    projectId: 'store-attendance-a7f2e',
    storageBucket: 'store-attendance-a7f2e.firebasestorage.app',
    iosBundleId: 'com.example.storeAttendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsetBFhJ1AiFRD382RmOc59nxY3i0oNag',
    appId: '1:663044881481:ios:db33bc21fb1551fbec9398',
    messagingSenderId: '663044881481',
    projectId: 'store-attendance-a7f2e',
    storageBucket: 'store-attendance-a7f2e.firebasestorage.app',
    iosBundleId: 'com.example.storeAttendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb7QD9AnVNc66nFy558eccRHdMnMPnRSA',
    appId: '1:663044881481:web:4ddf19263d5f1a71ec9398',
    messagingSenderId: '663044881481',
    projectId: 'store-attendance-a7f2e',
    authDomain: 'store-attendance-a7f2e.firebaseapp.com',
    storageBucket: 'store-attendance-a7f2e.firebasestorage.app',
    measurementId: 'G-CJR8S6C2S5',
  );
}
